--liquibase formatted sql

--changeset Neven Prašnikar:1
--Define tables.
CREATE TABLE public.category(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT CATEGORY_PKEY PRIMARY KEY (id), --If I remember my SQL correctly, *and* I'm not actually remembering a custom MySQL feature, all of Liquibase's constraint definitions (except the foreign key, maybe?) are unnecessarily verbose... but they work, and they're technically autogenerated, so I'll allow it.
    UNIQUE (name) --Presumably we don't want two categories sharing the same name.
);

CREATE TABLE public.joke(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content VARCHAR(65535) NOT NULL,
    likes INTEGER DEFAULT 0,
    dislikes INTEGER DEFAULT 0,
    category INTEGER NOT NULL,
    CONSTRAINT JOKE_PKEY PRIMARY KEY (id),
    CONSTRAINT fk_category_id FOREIGN KEY (category) REFERENCES public.category(id)
);

--changeset Neven Prašnikar:2
--Define joke categories. This is one of the places where Groovy seems drastically less efficient than writing SQL directly...
INSERT INTO public.category (name) VALUES ('Chuck Norris'), ('Škola'), ('Mujo');

--changeset Neven Prašnikar:3
--Define first joke. (I could technically roll the subsequent joke definitions into this one, but I feel like that would not accurately represent how I approached this.
INSERT INTO public.joke(category, content, likes, dislikes) VALUES
(
    (SELECT id FROM category WHERE name = 'Chuck Norris'), --We have no guarantee that Chuck Norris jokes will have an externally predictable category ID. They probably will, but they don't have to.
    E'Zašto je Chuck Norris najjači?\nZato što vježba dva dana dnevno.',
    72,
    10
);

--changeset Neven Prašnikar:4
--Add the other default jokes.
INSERT INTO public.joke(category, content, likes, dislikes) VALUES
(
    (SELECT id FROM category WHERE name = 'Škola'),
    E'Pita nastavnica hrvatskog jezika mladog osnovnoškolca:\nReci ti meni što su to prilozi?\nPrilozi su: ketchup, majoneza, luk, salata...',
    80,
    40
),
(
    (SELECT id FROM category WHERE name = 'Škola'),
    E'Pričaju dvije gimnazijalke:\nNema mi roditelja doma ovaj vikend!\nBože, pa koja si ti sretnica! Možeš učiti naglas!',
    25,
    2
),
(
    (SELECT id FROM category WHERE name = 'Mujo'),
    E'Došao Mujo u pizzeriju i naručio pizzu. Konobar ga upita:\nŽelite da vam izrežem pizzu na 6 ili 12 komada?\nMa na 6 komada, nema šanse da pojedem 12.',
    32,
    9
);

--changeset Neven Prašnikar:5
--Add another joke, since the assignment specified 5 jokes and I was only able to, ehm, 'borrow' 4 of them.
INSERT INTO category(name) VALUES('Overused Classics'); --Because of course those would be the only kind I know...
INSERT INTO joke(category, content, likes, dislikes) VALUES
(
    (SELECT id FROM category WHERE name = 'Overused Classics'),
    E'Why did the chicken cross the road?\nTo get to the other side!',
    4,
    17
)